package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/shakestzd/wipnote/core/htmlparse"
	"github.com/shakestzd/wipnote/core/models"
	"github.com/spf13/cobra"
)

// purgeSpikesCmd scans .wipnote/spikes/, identifies stale todo spikes, and
// deletes them. Kept spikes: done/in-progress, track-linked, or manual filenames.
func purgeSpikesCmd() *cobra.Command {
	var dryRun bool

	cmd := &cobra.Command{
		Use:   "purge-spikes",
		Short: "Remove stale todo spikes, keeping linked and done spikes",
		Long: `Scans .wipnote/spikes/ and deletes stale todo spikes.

A spike is KEPT if any of the following are true:
  - Status is done or in-progress
  - data-track-id attribute is non-empty
  - The spike ID appears in any track's contains edges
  - The filename does not follow the auto-generated spk-XXXXXXXX.html pattern

Deleting the HTML file is the whole operation: .wipnote/ is the canonical
store, so a purged spike is gone the moment its file is. Nothing has to be
resynced afterwards.`,
		RunE: func(cmd *cobra.Command, _ []string) error {
			return runPurgeSpikes(cmd, dryRun)
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false,
		"Show what would be deleted without deleting")
	return cmd
}

func runPurgeSpikes(cmd *cobra.Command, dryRun bool) error {
	wipnoteDir, err := findWipnoteDir()
	if err != nil {
		return err
	}

	spikesDir := filepath.Join(wipnoteDir, "spikes")

	// 1. Build the set of spike IDs linked from any track.
	linkedFromTrack, err := collectTrackLinkedSpikeIDs(wipnoteDir)
	if err != nil {
		return fmt.Errorf("scan tracks: %w", err)
	}

	// 2. Scan all spike files.
	pattern := filepath.Join(spikesDir, "*.html")
	files, err := filepath.Glob(pattern)
	if err != nil {
		return fmt.Errorf("glob spikes: %w", err)
	}

	total := len(files)
	fmt.Fprintf(cmd.OutOrStdout(), "Scanning %s... %d spikes found\n", spikesDir, total)

	var toKeep, toDelete []string
	var keepReasons []string

	for _, f := range files {
		keep, reason := shouldKeepSpike(f, linkedFromTrack)
		if keep {
			toKeep = append(toKeep, f)
			keepReasons = append(keepReasons, reason)
		} else {
			toDelete = append(toDelete, f)
		}
	}

	fmt.Fprintf(cmd.OutOrStdout(), "Keeping: %d\n", len(toKeep))
	fmt.Fprintf(cmd.OutOrStdout(), "Deleting: %d stale todo spikes\n", len(toDelete))

	if dryRun {
		fmt.Fprintf(cmd.OutOrStdout(),
			"\n[dry-run] Would delete %d files. Run without --dry-run to execute.\n",
			len(toDelete))
		if len(toKeep) > 0 {
			fmt.Fprintln(cmd.OutOrStdout(), "\nKept spikes:")
			for i, f := range toKeep {
				fmt.Fprintf(cmd.OutOrStdout(), "  %-40s  (%s)\n",
					filepath.Base(f), keepReasons[i])
			}
		}
		return nil
	}

	// 3. Delete the stale spikes.
	deleted := 0
	for _, f := range toDelete {
		if err := os.Remove(f); err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "warning: delete %s: %v\n",
				filepath.Base(f), err)
			continue
		}
		deleted++
	}

	// Deleting the file is the complete operation. The purge used to end with
	// a full reindex to sync a per-project SQLite file; there is no such file
	// any more, and the in-memory projection every command builds is derived
	// from whatever HTML is on disk at the time it runs (feat-fc3cc9e0).
	fmt.Fprintf(cmd.OutOrStdout(), "\nDeleted %d stale spikes. %d spikes remaining.\n",
		deleted, len(toKeep))
	return nil
}

// shouldKeepSpike returns (true, reason) if the spike should be kept.
// Returns (false, "") if it should be deleted.
func shouldKeepSpike(filePath string, linkedFromTrack map[string]bool) (bool, string) {
	base := filepath.Base(filePath)

	// Keep spikes with non-standard filenames (manually created investigations).
	if !isAutoGeneratedSpikeFile(base) {
		return true, "manual filename"
	}

	node, err := htmlparse.ParseFile(filePath)
	if err != nil {
		// Cannot parse — keep to be safe.
		return true, "parse error"
	}

	// Keep if status is not todo.
	if node.Status != models.StatusTodo {
		return true, fmt.Sprintf("status=%s", node.Status)
	}

	// Keep if data-track-id is set.
	if node.TrackID != "" {
		return true, fmt.Sprintf("track=%s", node.TrackID)
	}

	// Keep if the spike ID appears in any track's contains edges.
	if linkedFromTrack[node.ID] {
		return true, "linked from track"
	}

	return false, ""
}

// isAutoGeneratedSpikeFile returns true if the filename matches the pattern
// spk-XXXXXXXX.html (exactly 8 lowercase hex chars after the prefix).
func isAutoGeneratedSpikeFile(filename string) bool {
	if !strings.HasPrefix(filename, "spk-") || !strings.HasSuffix(filename, ".html") {
		return false
	}
	inner := strings.TrimPrefix(strings.TrimSuffix(filename, ".html"), "spk-")
	if len(inner) != 8 {
		return false
	}
	for _, c := range inner {
		isHex := (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')
		if !isHex {
			return false
		}
	}
	return true
}

// collectTrackLinkedSpikeIDs scans all track HTML files and returns the set of
// spike IDs (spk-*) that appear in any track's graph edges.
func collectTrackLinkedSpikeIDs(wipnoteDir string) (map[string]bool, error) {
	linked := make(map[string]bool)

	pattern := filepath.Join(wipnoteDir, "tracks", "*.html")
	files, err := filepath.Glob(pattern)
	if err != nil {
		return linked, fmt.Errorf("glob tracks: %w", err)
	}

	for _, f := range files {
		node, parseErr := htmlparse.ParseFile(f)
		if parseErr != nil {
			continue
		}
		for _, edges := range node.Edges {
			for _, e := range edges {
				if strings.HasPrefix(e.TargetID, "spk-") {
					linked[e.TargetID] = true
				}
			}
		}
	}

	return linked, nil
}
