// Code generated by TestDumpEphemeralSchema. DO NOT EDIT.
//
// This is the schema produced by running the migration chain in
// migrations.go against an empty database, captured so that opening an
// ephemeral projection does not have to run that chain.
//
// Regenerate after ANY migration change:
//
//	WIPNOTE_DUMP_SCHEMA=$PWD/db/ephemeral_schema_gen.go \
//	  go test -run TestDumpEphemeralSchema ./db/
//
// TestEphemeralSchemaMatchesMigrations fails if this file drifts from the
// migration chain, so a forgotten regeneration is caught by the suite.

package db

// generatedSchemaVersion is the user_version this snapshot corresponds to.
const generatedSchemaVersion = 23

// generatedTablesDDL creates every table, in migration order.
var generatedTablesDDL = []string{
	"CREATE TABLE agent_events (\n\t\t\tevent_id TEXT PRIMARY KEY,\n\t\t\tagent_id TEXT NOT NULL,\n\t\t\tevent_type TEXT NOT NULL CHECK(\n\t\t\t\tevent_type IN ('tool_call','tool_result','error','delegation',\n\t\t\t\t               'completion','start','end','check_point','task_delegation',\n\t\t\t\t               'teammate_idle','task_created','task_completed','quality_gate',\n\t\t\t\t               'claim.proposed','claim.claimed','claim.heartbeat','claim.blocked',\n\t\t\t\t               'claim.completed','claim.abandoned','claim.expired','claim.handoff')\n\t\t\t),\n\t\t\ttimestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\ttool_name TEXT,\n\t\t\tinput_summary TEXT,\n\t\t\ttool_input JSON,\n\t\t\toutput_summary TEXT,\n\t\t\tcontext JSON,\n\t\t\tsession_id TEXT NOT NULL,\n\t\t\tfeature_id TEXT,\n\t\t\tparent_agent_id TEXT,\n\t\t\tparent_event_id TEXT,\n\t\t\tsubagent_type TEXT,\n\t\t\tchild_spike_count INTEGER DEFAULT 0,\n\t\t\tcost_tokens INTEGER DEFAULT 0,\n\t\t\texecution_duration_seconds REAL DEFAULT 0.0,\n\t\t\tstatus TEXT DEFAULT 'recorded',\n\t\t\tmodel TEXT,\n\t\t\tclaude_task_id TEXT,\n\t\t\tsource TEXT DEFAULT 'hook',\n\t\t\tstep_id TEXT,\n\t\t\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tupdated_at DATETIME DEFAULT CURRENT_TIMESTAMP, reason TEXT, teammate_name TEXT, team_name TEXT, prompt_id TEXT,\n\t\t\tCHECK (NOT (event_type = 'tool_call' AND agent_id = 'human' AND (tool_name IS NULL OR tool_name != 'UserQuery'))),\n\t\t\tFOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE ON UPDATE CASCADE,\n\t\t\tFOREIGN KEY (feature_id) REFERENCES features(id) ON DELETE SET NULL ON UPDATE CASCADE\n\t\t)",
	"CREATE TABLE features (\n\t\t\tid TEXT PRIMARY KEY,\n\t\t\ttype TEXT NOT NULL CHECK(\n\t\t\t\ttype IN ('feature','bug','spike','chore','epic','task','plan','spec')\n\t\t\t),\n\t\t\ttitle TEXT NOT NULL,\n\t\t\tdescription TEXT,\n\t\t\tstatus TEXT NOT NULL DEFAULT 'todo' CHECK(\n\t\t\t\tstatus IN ('todo','in-progress','blocked','done','active','ended','stale')\n\t\t\t),\n\t\t\tpriority TEXT DEFAULT 'medium' CHECK(\n\t\t\t\tpriority IN ('low','medium','high','critical')\n\t\t\t),\n\t\t\tassigned_to TEXT,\n\t\t\tassignee TEXT DEFAULT NULL,\n\t\t\ttrack_id TEXT,\n\t\t\tcreated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tupdated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tcompleted_at DATETIME,\n\t\t\tsteps_total INTEGER DEFAULT 0,\n\t\t\tsteps_completed INTEGER DEFAULT 0,\n\t\t\tparent_feature_id TEXT,\n\t\t\ttags JSON,\n\t\t\tmetadata JSON,\n\t\t\tFOREIGN KEY (track_id) REFERENCES tracks(id),\n\t\t\tFOREIGN KEY (parent_feature_id) REFERENCES features(id)\n\t\t)",
	"CREATE TABLE sessions (\n\t\t\tsession_id TEXT PRIMARY KEY,\n\t\t\tagent_assigned TEXT NOT NULL,\n\t\t\tparent_session_id TEXT,\n\t\t\tparent_event_id TEXT,\n\t\t\tcreated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tcompleted_at DATETIME,\n\t\t\ttotal_events INTEGER DEFAULT 0,\n\t\t\ttotal_tokens_used INTEGER DEFAULT 0,\n\t\t\tcontext_drift REAL DEFAULT 0.0,\n\t\t\tstatus TEXT NOT NULL DEFAULT 'active' CHECK(\n\t\t\t\tstatus IN ('active','completed','paused','failed')\n\t\t\t),\n\t\t\ttranscript_id TEXT,\n\t\t\ttranscript_path TEXT,\n\t\t\ttranscript_synced DATETIME,\n\t\t\tstart_commit TEXT,\n\t\t\tend_commit TEXT,\n\t\t\tis_subagent BOOLEAN DEFAULT FALSE,\n\t\t\tfeatures_worked_on JSON,\n\t\t\tmetadata JSON,\n\t\t\tlast_user_query_at DATETIME,\n\t\t\tlast_user_query TEXT,\n\t\t\thandoff_notes TEXT,\n\t\t\trecommended_next TEXT,\n\t\t\tblockers JSON,\n\t\t\trecommended_context JSON,\n\t\t\tcontinued_from TEXT,\n\t\t\tsession_family_id TEXT,\n\t\t\tcost_budget REAL,\n\t\t\tcost_threshold_breached INTEGER DEFAULT 0,\n\t\t\tpredicted_cost REAL DEFAULT 0.0,\n\t\t\tmodel TEXT,\n\t\t\tactive_feature_id TEXT,\n\t\t\tupdated_at DATETIME,\n\t\t\texec_worktree_path TEXT,\n\t\t\tbranch TEXT,\n\t\t\tharness TEXT, title TEXT, git_remote_url TEXT, project_dir TEXT,\n\t\t\tFOREIGN KEY (parent_session_id) REFERENCES sessions(session_id) ON DELETE SET NULL ON UPDATE CASCADE,\n\t\t\tFOREIGN KEY (parent_event_id) REFERENCES agent_events(event_id) ON DELETE SET NULL ON UPDATE CASCADE,\n\t\t\tFOREIGN KEY (continued_from) REFERENCES sessions(session_id) ON DELETE SET NULL ON UPDATE CASCADE\n\t\t)",
	"CREATE TABLE tracks (\n\t\t\tid TEXT PRIMARY KEY,\n\t\t\ttype TEXT DEFAULT 'track',\n\t\t\ttitle TEXT NOT NULL,\n\t\t\tdescription TEXT,\n\t\t\tpriority TEXT DEFAULT 'medium' CHECK(\n\t\t\t\tpriority IN ('low','medium','high','critical')\n\t\t\t),\n\t\t\tstatus TEXT NOT NULL DEFAULT 'todo' CHECK(\n\t\t\t\tstatus IN ('todo','in-progress','blocked','done','active','ended','stale')\n\t\t\t),\n\t\t\tcreated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tupdated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tcompleted_at DATETIME,\n\t\t\tfeatures JSON,\n\t\t\tmetadata JSON\n\t\t)",
	"CREATE TABLE claims (\n\t\t\tclaim_id TEXT PRIMARY KEY,\n\t\t\twork_item_id TEXT NOT NULL,\n\t\t\ttrack_id TEXT,\n\t\t\towner_session_id TEXT NOT NULL,\n\t\t\towner_agent TEXT NOT NULL DEFAULT 'claude-code',\n\t\t\tstatus TEXT NOT NULL DEFAULT 'proposed' CHECK(\n\t\t\t\tstatus IN ('proposed','claimed','in_progress','blocked',\n\t\t\t\t           'handoff_pending','completed','abandoned','expired','rejected')\n\t\t\t),\n\t\t\tintended_output TEXT,\n\t\t\twrite_scope JSON,\n\t\t\tleased_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tlease_expires_at DATETIME NOT NULL,\n\t\t\tlast_heartbeat_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tdependencies JSON,\n\t\t\tprogress_notes TEXT,\n\t\t\tblocker_reason TEXT,\n\t\t\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tupdated_at DATETIME DEFAULT CURRENT_TIMESTAMP, claimed_by_agent_id TEXT DEFAULT \"\",\n\t\t\tFOREIGN KEY (work_item_id) REFERENCES features(id) ON DELETE CASCADE,\n\t\t\tFOREIGN KEY (owner_session_id) REFERENCES sessions(session_id) ON DELETE CASCADE\n\t\t)",
	"CREATE TABLE graph_edges (\n\t\t\tedge_id TEXT PRIMARY KEY,\n\t\t\tfrom_node_id TEXT NOT NULL,\n\t\t\tfrom_node_type TEXT NOT NULL,\n\t\t\tto_node_id TEXT NOT NULL,\n\t\t\tto_node_type TEXT NOT NULL,\n\t\t\trelationship_type TEXT NOT NULL,\n\t\t\tweight REAL DEFAULT 1.0,\n\t\t\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tmetadata JSON\n\t\t)",
	"CREATE TABLE git_commits (\n\t\t\tcommit_hash TEXT NOT NULL,\n\t\t\tsession_id TEXT NOT NULL,\n\t\t\tfeature_id TEXT NOT NULL DEFAULT '',\n\t\t\ttool_event_id TEXT,\n\t\t\tmessage TEXT,\n\t\t\ttimestamp DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tPRIMARY KEY (commit_hash, session_id, feature_id)\n\t\t)",
	"CREATE TABLE live_events (\n\t\t\tid INTEGER PRIMARY KEY AUTOINCREMENT,\n\t\t\tevent_type TEXT NOT NULL,\n\t\t\tevent_data TEXT NOT NULL,\n\t\t\tparent_event_id TEXT,\n\t\t\tsession_id TEXT,\n\t\t\tspawner_type TEXT,\n\t\t\tcreated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,\n\t\t\tbroadcast_at TIMESTAMP\n\t\t)",
	"CREATE TABLE agent_lineage_trace (\n\t\t\ttrace_id TEXT PRIMARY KEY,\n\t\t\troot_session_id TEXT NOT NULL,\n\t\t\tsession_id TEXT,\n\t\t\tagent_name TEXT,\n\t\t\tdepth INTEGER DEFAULT 0,\n\t\t\tpath TEXT,\n\t\t\tfeature_id TEXT,\n\t\t\tstarted_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tcompleted_at DATETIME,\n\t\t\tstatus TEXT DEFAULT 'active'\n\t\t)",
	"CREATE TABLE messages (\n\t\t\tid INTEGER PRIMARY KEY AUTOINCREMENT,\n\t\t\tsession_id TEXT NOT NULL,\n\t\t\tordinal INTEGER NOT NULL,\n\t\t\trole TEXT NOT NULL CHECK(role IN ('user','assistant')),\n\t\t\tcontent TEXT NOT NULL DEFAULT '',\n\t\t\ttimestamp DATETIME,\n\t\t\thas_thinking INTEGER DEFAULT 0,\n\t\t\thas_tool_use INTEGER DEFAULT 0,\n\t\t\tcontent_length INTEGER DEFAULT 0,\n\t\t\tmodel TEXT,\n\t\t\tinput_tokens INTEGER DEFAULT 0,\n\t\t\toutput_tokens INTEGER DEFAULT 0,\n\t\t\tcache_read_tokens INTEGER DEFAULT 0,\n\t\t\tstop_reason TEXT,\n\t\t\tuuid TEXT,\n\t\t\tparent_uuid TEXT, agent_id TEXT,\n\t\t\tUNIQUE(session_id, ordinal)\n\t\t)",
	"CREATE TABLE tool_calls (\n\t\t\tid INTEGER PRIMARY KEY AUTOINCREMENT,\n\t\t\tmessage_id INTEGER REFERENCES messages(id) ON DELETE CASCADE,\n\t\t\tsession_id TEXT NOT NULL,\n\t\t\ttool_name TEXT NOT NULL,\n\t\t\tcategory TEXT NOT NULL DEFAULT 'Other',\n\t\t\ttool_use_id TEXT,\n\t\t\tinput_json TEXT,\n\t\t\tresult_content_length INTEGER DEFAULT 0,\n\t\t\tsubagent_session_id TEXT,\n\t\t\tfeature_id TEXT\n\t\t)",
	"CREATE TABLE feature_files (\n\t\t\tid TEXT PRIMARY KEY,\n\t\t\tfeature_id TEXT NOT NULL,\n\t\t\tfile_path TEXT NOT NULL,\n\t\t\toperation TEXT NOT NULL DEFAULT 'unknown',\n\t\t\tsession_id TEXT,\n\t\t\tfirst_seen DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tlast_seen DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tUNIQUE(feature_id, file_path)\n\t\t)",
	"CREATE TABLE session_files (\n\t\t\tid TEXT PRIMARY KEY,\n\t\t\tsession_id TEXT NOT NULL,\n\t\t\tfile_path TEXT NOT NULL,\n\t\t\toperation TEXT NOT NULL DEFAULT 'unknown',\n\t\t\tfirst_seen DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tlast_seen DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tcreated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n\t\t\tUNIQUE(session_id, file_path)\n\t\t)",
	"CREATE TABLE metadata (\n\t\t\tkey TEXT PRIMARY KEY,\n\t\t\tvalue TEXT NOT NULL,\n\t\t\tupdated_at TEXT DEFAULT (datetime('now'))\n\t\t)",
	"CREATE TABLE plan_feedback (\n\t\t\tid INTEGER PRIMARY KEY AUTOINCREMENT,\n\t\t\tplan_id TEXT NOT NULL,\n\t\t\tsection TEXT NOT NULL,\n\t\t\taction TEXT NOT NULL,\n\t\t\tvalue TEXT,\n\t\t\tquestion_id TEXT NOT NULL DEFAULT '',\n\t\t\tanchor TEXT NOT NULL DEFAULT '',\n\t\t\tconsumed INTEGER NOT NULL DEFAULT 0,\n\t\t\tresolved INTEGER NOT NULL DEFAULT 0,\n\t\t\tresolution_target TEXT NOT NULL DEFAULT '',\n\t\t\tcreated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tupdated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tUNIQUE(plan_id, section, action, question_id)\n\t\t)",
	"CREATE TABLE arch_cards (\n\t\t\tslug           TEXT PRIMARY KEY,\n\t\t\tkind           TEXT NOT NULL,\n\t\t\tpaths_json     TEXT NOT NULL DEFAULT '[]',\n\t\t\tverified_at    TEXT NOT NULL DEFAULT '',\n\t\t\tlinks_json     TEXT NOT NULL DEFAULT '[]',\n\t\t\tcreated_by     TEXT NOT NULL DEFAULT '',\n\t\t\tsuperseded_by  TEXT NOT NULL DEFAULT '',\n\t\t\tretired        INTEGER NOT NULL DEFAULT 0,\n\t\t\tbody           TEXT NOT NULL DEFAULT '',\n\t\t\tcreated_at     DATETIME,\n\t\t\tupdated_at     DATETIME,\n\t\t\tindexed_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP\n\t\t)",
	"CREATE TABLE claim_episodes (\n\t\t\tepisode_id      TEXT PRIMARY KEY,\n\t\t\twork_item_id    TEXT NOT NULL,\n\t\t\tsession_id      TEXT NOT NULL,\n\t\t\troot_session_id TEXT NOT NULL DEFAULT '',\n\t\t\tagent_id        TEXT NOT NULL,\n\t\t\tstarted_at      TEXT NOT NULL,\n\t\t\tended_at        TEXT NOT NULL DEFAULT '',\n\t\t\toutcome         TEXT NOT NULL DEFAULT '',\n\t\t\tsource_file     TEXT NOT NULL DEFAULT '',\n\t\t\tindexed_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP\n\t\t)",
	"CREATE TABLE gate_records (\n\t\t\tid INTEGER PRIMARY KEY AUTOINCREMENT,\n\t\t\trecord_id TEXT NOT NULL DEFAULT '',\n\t\t\tsession_id TEXT NOT NULL,\n\t\t\twork_item_id TEXT,\n\t\t\tharness TEXT,\n\t\t\tproject_type TEXT NOT NULL,\n\t\t\tgate_command TEXT NOT NULL,\n\t\t\tstatus TEXT NOT NULL CHECK(status IN ('pass','fail')),\n\t\t\tchecked_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\t\tsignature TEXT NOT NULL,\n\t\t\tallowlist_hits_json TEXT NOT NULL DEFAULT '[]',\n\t\t\tallowlist_hit_count INTEGER NOT NULL DEFAULT 0,\n\t\t\tsource TEXT NOT NULL DEFAULT 'check',\n\t\t\toutput_summary TEXT,\n\t\t\tprofile_signature TEXT NOT NULL DEFAULT '',\n\t\t\tguards_run TEXT NOT NULL DEFAULT '[]'\n\t\t)",
	"CREATE TABLE recaps (\n\t\t\tid            TEXT PRIMARY KEY,\n\t\t\tkind          TEXT NOT NULL DEFAULT '',\n\t\t\tinput         TEXT NOT NULL DEFAULT '',\n\t\t\tgit_range     TEXT NOT NULL DEFAULT '',\n\t\t\tgrounded      INTEGER NOT NULL DEFAULT 0,\n\t\t\ttitle         TEXT NOT NULL DEFAULT '',\n\t\t\toutcome       TEXT NOT NULL DEFAULT '',\n\t\t\twork_item_id  TEXT NOT NULL DEFAULT '',\n\t\t\tcreated_at    DATETIME,\n\t\t\tupdated_at    DATETIME,\n\t\t\tindexed_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP\n\t\t)",
	"CREATE TABLE otel_signals (\n\t\t\tsignal_id             TEXT PRIMARY KEY,\n\t\t\tharness               TEXT NOT NULL,\n\t\t\tsession_id            TEXT NOT NULL,\n\t\t\tprompt_id             TEXT,\n\t\t\ttrace_id              TEXT,\n\t\t\tspan_id               TEXT,\n\t\t\tparent_span           TEXT,\n\t\t\tkind                  TEXT NOT NULL CHECK(kind IN ('metric','log','span')),\n\t\t\tcanonical             TEXT NOT NULL,\n\t\t\tnative                TEXT NOT NULL,\n\t\t\tts_micros             INTEGER NOT NULL,\n\t\t\ttool_name             TEXT,\n\t\t\ttool_use_id           TEXT,\n\t\t\tmodel                 TEXT,\n\t\t\tdecision              TEXT,\n\t\t\tdecision_source       TEXT,\n\t\t\ttokens_in             INTEGER,\n\t\t\ttokens_out            INTEGER,\n\t\t\ttokens_cache_read     INTEGER,\n\t\t\ttokens_cache_creation INTEGER,\n\t\t\ttokens_thought        INTEGER,\n\t\t\ttokens_tool           INTEGER,\n\t\t\ttokens_reasoning      INTEGER,\n\t\t\tcost_usd              REAL,\n\t\t\tcost_source           TEXT CHECK(cost_source IS NULL OR cost_source IN ('vendor','derived','unknown')),\n\t\t\tduration_ms           INTEGER,\n\t\t\tsuccess               INTEGER,\n\t\t\terror_msg             TEXT,\n\t\t\tattempt               INTEGER,\n\t\t\tstatus_code           INTEGER,\n\t\t\tattrs_json            TEXT NOT NULL,\n\t\t\tcreated_at            INTEGER NOT NULL DEFAULT (strftime('%s','now') * 1000000), feature_id TEXT, agent_id TEXT,\n\t\t\tFOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE ON UPDATE CASCADE\n\t\t)",
	"CREATE TABLE otel_resource_attrs (\n\t\t\tsession_id TEXT NOT NULL,\n\t\t\tharness    TEXT NOT NULL,\n\t\t\tkey        TEXT NOT NULL,\n\t\t\tvalue      TEXT NOT NULL,\n\t\t\tobserved_at INTEGER NOT NULL DEFAULT (strftime('%s','now') * 1000000),\n\t\t\tPRIMARY KEY (session_id, key),\n\t\t\tFOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE ON UPDATE CASCADE\n\t\t)",
	"CREATE TABLE otel_session_rollup (\n\t\t\tsession_id                   TEXT PRIMARY KEY,\n\t\t\tharness                      TEXT NOT NULL,\n\t\t\ttotal_cost_usd               REAL,\n\t\t\ttotal_tokens_in              INTEGER,\n\t\t\ttotal_tokens_out             INTEGER,\n\t\t\ttotal_tokens_cache_read      INTEGER,\n\t\t\ttotal_tokens_cache_creation  INTEGER,\n\t\t\ttotal_tokens_thought         INTEGER,\n\t\t\ttotal_tokens_tool            INTEGER,\n\t\t\ttotal_tokens_reasoning       INTEGER,\n\t\t\ttotal_turns                  INTEGER,\n\t\t\ttotal_tool_calls             INTEGER,\n\t\t\ttotal_api_calls              INTEGER,\n\t\t\ttotal_api_errors             INTEGER,\n\t\t\tmax_attempt                  INTEGER,\n\t\t\tmaterialized_at              INTEGER NOT NULL,\n\t\t\tFOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE ON UPDATE CASCADE\n\t\t)",
	"CREATE TABLE pending_subagent_starts (\n\t\tagent_id          TEXT PRIMARY KEY,\n\t\tagent_type        TEXT NOT NULL,\n\t\tsession_id        TEXT NOT NULL,\n\t\tcwd               TEXT,\n\t\tparent_agent_id   TEXT,\n\t\tcreated_at        INTEGER NOT NULL,\n\t\tconsumed_at       INTEGER,\n\t\tagent_span_id     TEXT\n\t)",
	"CREATE TABLE active_work_items (\n\t\tsession_id    TEXT NOT NULL,\n\t\tagent_id      TEXT NOT NULL,\n\t\twork_item_id  TEXT NOT NULL,\n\t\tclaimed_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,\n\t\tPRIMARY KEY (session_id, agent_id)\n\t)",
}

// generatedAuxDDL creates every index, trigger and view.
var generatedAuxDDL = []string{
	"CREATE INDEX idx_agent_events_session_ts_desc ON agent_events(session_id, timestamp DESC)",
	"CREATE INDEX idx_agent_events_agent_ts_desc ON agent_events(agent_id, timestamp DESC)",
	"CREATE INDEX idx_agent_events_agent ON agent_events(agent_id)",
	"CREATE INDEX idx_agent_events_type ON agent_events(event_type)",
	"CREATE INDEX idx_agent_events_parent_event ON agent_events(parent_event_id)",
	"CREATE INDEX idx_agent_events_task_delegation ON agent_events(event_type, subagent_type, timestamp DESC)",
	"CREATE INDEX idx_agent_events_session_tool ON agent_events(session_id, tool_name)",
	"CREATE INDEX idx_agent_events_timestamp ON agent_events(timestamp DESC)",
	"CREATE INDEX idx_agent_events_claude_task_id ON agent_events(claude_task_id)",
	"CREATE INDEX idx_agent_events_step_id ON agent_events(step_id)",
	"CREATE INDEX idx_features_status_priority ON features(status, priority DESC, created_at DESC)",
	"CREATE INDEX idx_features_track_priority ON features(track_id, priority DESC, created_at DESC)",
	"CREATE INDEX idx_features_assigned ON features(assigned_to)",
	"CREATE INDEX idx_features_parent ON features(parent_feature_id)",
	"CREATE INDEX idx_features_type ON features(type)",
	"CREATE INDEX idx_features_created ON features(created_at DESC)",
	"CREATE INDEX idx_sessions_agent_created ON sessions(agent_assigned, created_at DESC)",
	"CREATE INDEX idx_sessions_family ON sessions(session_family_id)",
	"CREATE INDEX idx_sessions_status_created ON sessions(status, created_at DESC)",
	"CREATE INDEX idx_sessions_parent ON sessions(parent_session_id, created_at DESC)",
	"CREATE INDEX idx_sessions_created ON sessions(created_at DESC)",
	"CREATE INDEX idx_tracks_status_created ON tracks(status, created_at DESC)",
	"CREATE INDEX idx_tracks_priority ON tracks(priority DESC)",
	"CREATE INDEX idx_claims_work_item ON claims(work_item_id)",
	"CREATE INDEX idx_claims_session ON claims(owner_session_id)",
	"CREATE INDEX idx_claims_status ON claims(status)",
	"CREATE INDEX idx_claims_lease_expiry ON claims(lease_expires_at)",
	"CREATE INDEX idx_edges_from ON graph_edges(from_node_id)",
	"CREATE INDEX idx_edges_to ON graph_edges(to_node_id)",
	"CREATE INDEX idx_edges_type ON graph_edges(relationship_type)",
	"CREATE INDEX idx_git_commits_feature ON git_commits(feature_id)",
	"CREATE INDEX idx_live_events_pending ON live_events(broadcast_at) WHERE broadcast_at IS NULL",
	"CREATE INDEX idx_live_events_created ON live_events(created_at DESC)",
	"CREATE INDEX idx_lineage_root ON agent_lineage_trace(root_session_id)",
	"CREATE INDEX idx_lineage_session ON agent_lineage_trace(session_id)",
	"CREATE INDEX idx_messages_session_ord ON messages(session_id, ordinal)",
	"CREATE INDEX idx_messages_session_role ON messages(session_id, role)",
	"CREATE INDEX idx_messages_timestamp ON messages(timestamp DESC)",
	"CREATE INDEX idx_tool_calls_session ON tool_calls(session_id)",
	"CREATE INDEX idx_tool_calls_message ON tool_calls(message_id)",
	"CREATE INDEX idx_tool_calls_name ON tool_calls(tool_name)",
	"CREATE INDEX idx_tool_calls_category ON tool_calls(category)",
	"CREATE INDEX idx_tool_calls_feature ON tool_calls(feature_id)",
	"CREATE INDEX idx_feature_files_feature ON feature_files(feature_id)",
	"CREATE INDEX idx_feature_files_path ON feature_files(file_path)",
	"CREATE INDEX idx_feature_files_path_seen ON feature_files(file_path, last_seen)",
	"CREATE INDEX idx_session_files_session ON session_files(session_id)",
	"CREATE INDEX idx_session_files_path ON session_files(file_path)",
	"CREATE INDEX idx_arch_cards_kind ON arch_cards(kind)",
	"CREATE INDEX idx_arch_cards_retired ON arch_cards(retired)",
	"CREATE INDEX idx_claim_episodes_agent_start ON claim_episodes(agent_id, started_at)",
	"CREATE INDEX idx_claim_episodes_session_agent ON claim_episodes(session_id, agent_id, started_at)",
	"CREATE INDEX idx_claim_episodes_work_item ON claim_episodes(work_item_id, started_at)",
	"CREATE INDEX idx_plan_feedback_plan_id ON plan_feedback(plan_id)",
	"CREATE INDEX idx_plan_feedback_section ON plan_feedback(plan_id, section)",
	"CREATE INDEX idx_gate_records_session_checked ON gate_records(session_id, checked_at DESC)",
	"CREATE INDEX idx_gate_records_work_item_checked ON gate_records(work_item_id, checked_at DESC)",
	"CREATE UNIQUE INDEX idx_gate_records_record_id ON gate_records(record_id) WHERE record_id != ''",
	"CREATE INDEX idx_recaps_kind ON recaps(kind)",
	"CREATE INDEX idx_recaps_work_item ON recaps(work_item_id)",
	"CREATE INDEX idx_otel_session_ts   ON otel_signals(session_id, ts_micros)",
	"CREATE INDEX idx_otel_prompt       ON otel_signals(prompt_id)",
	"CREATE INDEX idx_otel_canonical_ts ON otel_signals(canonical, ts_micros DESC)",
	"CREATE INDEX idx_otel_trace        ON otel_signals(trace_id)",
	"CREATE INDEX idx_otel_parent_span  ON otel_signals(parent_span)",
	"CREATE INDEX idx_otel_tool         ON otel_signals(session_id, tool_name, ts_micros)",
	"CREATE INDEX idx_otel_harness      ON otel_signals(harness, ts_micros DESC)",
	"CREATE INDEX idx_otel_model_ts     ON otel_signals(model, ts_micros) WHERE model IS NOT NULL",
	"CREATE INDEX idx_otel_span_id      ON otel_signals(span_id) WHERE span_id IS NOT NULL",
	"CREATE INDEX idx_otel_session_kind_ts ON otel_signals(session_id, kind, ts_micros DESC, created_at DESC, signal_id DESC)",
	"CREATE INDEX idx_pending_subagent_session ON pending_subagent_starts(session_id)",
	"CREATE INDEX idx_active_work_items_work_item\n\t\tON active_work_items(work_item_id)",
	"CREATE TRIGGER trg_increment_total_events\n\tAFTER INSERT ON agent_events\n\tFOR EACH ROW\n\tBEGIN\n\t\tUPDATE sessions\n\t\tSET total_events = total_events + 1\n\t\tWHERE session_id = NEW.session_id;\n\tEND",
	"CREATE INDEX idx_otel_feature_ts ON otel_signals(feature_id, ts_micros) WHERE feature_id IS NOT NULL",
	"CREATE INDEX idx_otel_agent_ts ON otel_signals(agent_id, ts_micros) WHERE agent_id IS NOT NULL",
}
